export enum DocumentStatus {
  DRAFT = "DRAFT",
  PUBLISHED = "PUBLISHED",
  ARCHIVED = "ARCHIVED",
  EXPIRED = "EXPIRED",
  UPLOADED = "UPLOADED",
  PARSING = "PARSING",
  CHUNKING = "CHUNKING",
  EMBEDDING = "EMBEDDING",
  INDEXING = "INDEXING",
  READY = "READY",
  FAILED = "FAILED",
}
