export enum ProcessingStatus {
  UPLOADED = "UPLOADED",
  PARSING = "PARSING",
  PARSED = "PARSED",
  CHUNKING = "CHUNKING",
  CHUNKED = "CHUNKED",
  EMBEDDING = "EMBEDDING",
  EMBEDDED = "EMBEDDED",
  INDEXING = "INDEXING",
  INDEXED = "INDEXED",
  READY = "READY",
  FAILED = "FAILED",
}
