package com.poliwise.feedback.enums;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    TOKEN_REFRESH,
    PASSWORD_CHANGE,
    USER_CREATE,
    USER_UPDATE,
    USER_DEACTIVATE,
    USER_ACTIVATE,
    USER_REVOKE,
    USER_DELETE,
    DOCUMENT_UPLOAD,
    DOCUMENT_UPDATE,
    DOCUMENT_DELETE,
    DOCUMENT_PUBLISH,
    DOCUMENT_ARCHIVE,
    DOCUMENT_VERSION_CREATE,
    QUESTION_ASK,
    CONVERSATION_CREATE,
    CONVERSATION_DELETE,
    FEEDBACK_SUBMIT,
    SETTINGS_UPDATE,
    BULK_IMPORT,
    REPORT_EXPORT
}
