export enum AuditAction {
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILED = "LOGIN_FAILED",
  LOGOUT = "LOGOUT",
  TOKEN_REFRESH = "TOKEN_REFRESH",
  PASSWORD_CHANGE = "PASSWORD_CHANGE",

  USER_CREATE = "USER_CREATE",
  USER_UPDATE = "USER_UPDATE",
  USER_DEACTIVATE = "USER_DEACTIVATE",
  USER_ACTIVATE = "USER_ACTIVATE",
  USER_REVOKE = "USER_REVOKE",
  USER_DELETE = "USER_DELETE",

  DOCUMENT_UPLOAD = "DOCUMENT_UPLOAD",
  DOCUMENT_UPDATE = "DOCUMENT_UPDATE",
  DOCUMENT_DELETE = "DOCUMENT_DELETE",
  DOCUMENT_PUBLISH = "DOCUMENT_PUBLISH",
  DOCUMENT_ARCHIVE = "DOCUMENT_ARCHIVE",
  DOCUMENT_VERSION_CREATE = "DOCUMENT_VERSION_CREATE",

  QUESTION_ASK = "QUESTION_ASK",

  CONVERSATION_CREATE = "CONVERSATION_CREATE",
  CONVERSATION_DELETE = "CONVERSATION_DELETE",

  FEEDBACK_SUBMIT = "FEEDBACK_SUBMIT",

  SETTINGS_UPDATE = "SETTINGS_UPDATE",

  BULK_IMPORT = "BULK_IMPORT",
  REPORT_EXPORT = "REPORT_EXPORT",
}
