export enum ReportType {
  USAGE_SUMMARY = "USAGE_SUMMARY",
  QUESTION_ANALYTICS = "QUESTION_ANALYTICS",
  FEEDBACK_ANALYSIS = "FEEDBACK_ANALYSIS",
  USER_ENGAGEMENT = "USER_ENGAGEMENT",
  DOCUMENT_POPULARITY = "DOCUMENT_POPULARITY",
  UNANSWERED_QUESTIONS = "UNANSWERED_QUESTIONS",
  DEPARTMENT_BREAKDOWN = "DEPARTMENT_BREAKDOWN",
}
