export enum ResourceType {
  USER = "USER",
  DOCUMENT = "DOCUMENT",
  CONVERSATION = "CONVERSATION",
  MESSAGE = "MESSAGE",
  FEEDBACK = "FEEDBACK",
  DEPARTMENT = "DEPARTMENT",
  CATEGORY = "CATEGORY",
  TAG = "TAG",
  SETTINGS = "SETTINGS",
}
