export enum LoginStatus {
  SUCCESS = "SUCCESS",

  FAILED_CREDENTIALS = "FAILED_CREDENTIALS",
  FAILED_DEACTIVATED = "FAILED_DEACTIVATED",
  FAILED_REVOKED = "FAILED_REVOKED",
  FAILED_LOCKED = "FAILED_LOCKED",
}
